version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: townfind-db
    environment:
      POSTGRES_USER: townfind
      POSTGRES_PASSWORD: townfind
      POSTGRES_DB: townfind
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: townfind-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  dbdata:
